version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: "build"
    assignees:
      - "daaa1k"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: "ci"
    assignees:
      - "daaa1k"
    open-pull-requests-limit: 5
