# Changes here will be overwritten by Copier
_commit: v0.1.14
_src_path: https://github.com/daaa1k/template-go
owner: daaa1k
project_description: Paste clipboard image as Markdown link
project_name: mdp
