# yaml-language-server: $schema=https://www.schemastore.org/prek.json

[[repos]]
hooks:
  - id: go-fmt
    name: go fmt
    language: system
    entry: gofmt -w
    types: [go]
    pass_filenames: true

  - id: go-vet
    name: go vet
    language: system
    entry: go vet ./...
    types: [go]
    pass_filenames: false
